CREATE DATABASE ADO_Library;  

use ADO_Library;

-- Books Table
CREATE TABLE Books (
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    Title NVARCHAR(255) NOT NULL,
    Author NVARCHAR(255) NOT NULL,
    ISBN NVARCHAR(13) NOT NULL UNIQUE,
    PublishedYear DATE NULL,
    Availability BIT NOT NULL DEFAULT 1,
    CreatedDate DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedDate DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);

CREATE INDEX IDX_Books_ISBN ON Books (ISBN);

-- Users Table
CREATE TABLE Users (
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    Password NVARCHAR(255) NOT NULL,
    PhoneNumber NVARCHAR(15) NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedDate DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);

CREATE INDEX IDX_Users_Email ON Users (Email);

-- Borrowings Table
CREATE TABLE Borrowings (
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    BookID UNIQUEIDENTIFIER NOT NULL,
    UserID UNIQUEIDENTIFIER NOT NULL,
    BorrowDate DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    ReturnDate DATETIME2 NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    UpdatedDate DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    FOREIGN KEY (BookID) REFERENCES Books(Id) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(Id) ON DELETE CASCADE
);
